// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.7.
// **********************************************************************

#ifndef __AUTHF_H_
#define __AUTHF_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{
    enum AUTH_STATE
    {
        AUTH_INIT = -127,
        AUTH_SUCC = 0,
        AUTH_PROTO_ERR = -100,
        AUTH_WRONG_OBJ = -101,
        AUTH_WRONG_AK = -102,
        AUTH_WRONG_TIME = -103,
        AUTH_NOT_SUPPORT_ENC = -104,
        AUTH_DEC_FAIL = -105,
        AUTH_ERROR = -106,
    };
    inline string etos(const AUTH_STATE & e)
    {
        switch(e)
        {
            case AUTH_INIT: return "AUTH_INIT";
            case AUTH_SUCC: return "AUTH_SUCC";
            case AUTH_PROTO_ERR: return "AUTH_PROTO_ERR";
            case AUTH_WRONG_OBJ: return "AUTH_WRONG_OBJ";
            case AUTH_WRONG_AK: return "AUTH_WRONG_AK";
            case AUTH_WRONG_TIME: return "AUTH_WRONG_TIME";
            case AUTH_NOT_SUPPORT_ENC: return "AUTH_NOT_SUPPORT_ENC";
            case AUTH_DEC_FAIL: return "AUTH_DEC_FAIL";
            case AUTH_ERROR: return "AUTH_ERROR";
            default: return "";
        }
    }
    inline int stoe(const string & s, AUTH_STATE & e)
    {
        if(s == "AUTH_INIT")  { e=AUTH_INIT; return 0;}
        if(s == "AUTH_SUCC")  { e=AUTH_SUCC; return 0;}
        if(s == "AUTH_PROTO_ERR")  { e=AUTH_PROTO_ERR; return 0;}
        if(s == "AUTH_WRONG_OBJ")  { e=AUTH_WRONG_OBJ; return 0;}
        if(s == "AUTH_WRONG_AK")  { e=AUTH_WRONG_AK; return 0;}
        if(s == "AUTH_WRONG_TIME")  { e=AUTH_WRONG_TIME; return 0;}
        if(s == "AUTH_NOT_SUPPORT_ENC")  { e=AUTH_NOT_SUPPORT_ENC; return 0;}
        if(s == "AUTH_DEC_FAIL")  { e=AUTH_DEC_FAIL; return 0;}
        if(s == "AUTH_ERROR")  { e=AUTH_ERROR; return 0;}

        return -1;
    }

    enum AUTH_TYPE
    {
        AUTH_TYPENONE = 0,
        AUTH_TYPELOCAL = 1,
    };
    inline string etos(const AUTH_TYPE & e)
    {
        switch(e)
        {
            case AUTH_TYPENONE: return "AUTH_TYPENONE";
            case AUTH_TYPELOCAL: return "AUTH_TYPELOCAL";
            default: return "";
        }
    }
    inline int stoe(const string & s, AUTH_TYPE & e)
    {
        if(s == "AUTH_TYPENONE")  { e=AUTH_TYPENONE; return 0;}
        if(s == "AUTH_TYPELOCAL")  { e=AUTH_TYPELOCAL; return 0;}

        return -1;
    }

    struct BasicAuthInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.BasicAuthInfo";
        }
        static string MD5()
        {
            return "55420b345e13da84aad635417b0d3f4b";
        }
        BasicAuthInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sObjName = "";
            sAccessKey = "";
            sSecretKey = "";
            sHashSecretKey2 = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            if (sObjName != "")
            {
                _os.write(sObjName, 1);
            }
            if (sAccessKey != "")
            {
                _os.write(sAccessKey, 2);
            }
            if (sSecretKey != "")
            {
                _os.write(sSecretKey, 3);
            }
            if (sHashSecretKey2 != "")
            {
                _os.write(sHashSecretKey2, 4);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sObjName, 1, false);
            _is.read(sAccessKey, 2, false);
            _is.read(sSecretKey, 3, false);
            _is.read(sHashSecretKey2, 4, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sObjName"] = tars::JsonOutput::writeJson(sObjName);
            p->value["sAccessKey"] = tars::JsonOutput::writeJson(sAccessKey);
            p->value["sSecretKey"] = tars::JsonOutput::writeJson(sSecretKey);
            p->value["sHashSecretKey2"] = tars::JsonOutput::writeJson(sHashSecretKey2);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sObjName,pObj->value["sObjName"], false);
            tars::JsonInput::readJson(sAccessKey,pObj->value["sAccessKey"], false);
            tars::JsonInput::readJson(sSecretKey,pObj->value["sSecretKey"], false);
            tars::JsonInput::readJson(sHashSecretKey2,pObj->value["sHashSecretKey2"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sObjName,"sObjName");
            _ds.display(sAccessKey,"sAccessKey");
            _ds.display(sSecretKey,"sSecretKey");
            _ds.display(sHashSecretKey2,"sHashSecretKey2");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sObjName, true);
            _ds.displaySimple(sAccessKey, true);
            _ds.displaySimple(sSecretKey, true);
            _ds.displaySimple(sHashSecretKey2, false);
            return _os;
        }
    public:
        std::string sObjName;
        std::string sAccessKey;
        std::string sSecretKey;
        std::string sHashSecretKey2;
    };
    inline bool operator==(const BasicAuthInfo&l, const BasicAuthInfo&r)
    {
        return l.sObjName == r.sObjName && l.sAccessKey == r.sAccessKey && l.sSecretKey == r.sSecretKey && l.sHashSecretKey2 == r.sHashSecretKey2;
    }
    inline bool operator!=(const BasicAuthInfo&l, const BasicAuthInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const BasicAuthInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,BasicAuthInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct BasicAuthPackage : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.BasicAuthPackage";
        }
        static string MD5()
        {
            return "aec8c996fb516fda7f88937d6a625c14";
        }
        BasicAuthPackage()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sObjName = "";
            sAccessKey = "";
            iTime = 0;
            sHashMethod = "sha1";
            sSignature = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sObjName, 1);
            _os.write(sAccessKey, 2);
            _os.write(iTime, 3);
            if (sHashMethod != "sha1")
            {
                _os.write(sHashMethod, 4);
            }
            if (sSignature != "")
            {
                _os.write(sSignature, 5);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sObjName, 1, true);
            _is.read(sAccessKey, 2, true);
            _is.read(iTime, 3, true);
            _is.read(sHashMethod, 4, false);
            _is.read(sSignature, 5, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sObjName"] = tars::JsonOutput::writeJson(sObjName);
            p->value["sAccessKey"] = tars::JsonOutput::writeJson(sAccessKey);
            p->value["iTime"] = tars::JsonOutput::writeJson(iTime);
            p->value["sHashMethod"] = tars::JsonOutput::writeJson(sHashMethod);
            p->value["sSignature"] = tars::JsonOutput::writeJson(sSignature);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sObjName,pObj->value["sObjName"], true);
            tars::JsonInput::readJson(sAccessKey,pObj->value["sAccessKey"], true);
            tars::JsonInput::readJson(iTime,pObj->value["iTime"], true);
            tars::JsonInput::readJson(sHashMethod,pObj->value["sHashMethod"], false);
            tars::JsonInput::readJson(sSignature,pObj->value["sSignature"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sObjName,"sObjName");
            _ds.display(sAccessKey,"sAccessKey");
            _ds.display(iTime,"iTime");
            _ds.display(sHashMethod,"sHashMethod");
            _ds.display(sSignature,"sSignature");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sObjName, true);
            _ds.displaySimple(sAccessKey, true);
            _ds.displaySimple(iTime, true);
            _ds.displaySimple(sHashMethod, true);
            _ds.displaySimple(sSignature, false);
            return _os;
        }
    public:
        std::string sObjName;
        std::string sAccessKey;
        tars::Int64 iTime;
        std::string sHashMethod;
        std::string sSignature;
    };
    inline bool operator==(const BasicAuthPackage&l, const BasicAuthPackage&r)
    {
        return l.sObjName == r.sObjName && l.sAccessKey == r.sAccessKey && l.iTime == r.iTime && l.sHashMethod == r.sHashMethod && l.sSignature == r.sSignature;
    }
    inline bool operator!=(const BasicAuthPackage&l, const BasicAuthPackage&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const BasicAuthPackage&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,BasicAuthPackage&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct TokenKey : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.TokenKey";
        }
        static string MD5()
        {
            return "0c1d945735360d4e3752e1b2d448ba0c";
        }
        TokenKey()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sApplication = "";
            sServer = "";
            sObjName = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sApplication, 1);
            _os.write(sServer, 2);
            _os.write(sObjName, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sApplication, 1, true);
            _is.read(sServer, 2, true);
            _is.read(sObjName, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sApplication"] = tars::JsonOutput::writeJson(sApplication);
            p->value["sServer"] = tars::JsonOutput::writeJson(sServer);
            p->value["sObjName"] = tars::JsonOutput::writeJson(sObjName);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sApplication,pObj->value["sApplication"], true);
            tars::JsonInput::readJson(sServer,pObj->value["sServer"], true);
            tars::JsonInput::readJson(sObjName,pObj->value["sObjName"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sApplication,"sApplication");
            _ds.display(sServer,"sServer");
            _ds.display(sObjName,"sObjName");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sApplication, true);
            _ds.displaySimple(sServer, true);
            _ds.displaySimple(sObjName, false);
            return _os;
        }
    public:
        std::string sApplication;
        std::string sServer;
        std::string sObjName;
    };
    inline bool operator==(const TokenKey&l, const TokenKey&r)
    {
        return l.sApplication == r.sApplication && l.sServer == r.sServer && l.sObjName == r.sObjName;
    }
    inline bool operator!=(const TokenKey&l, const TokenKey&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const TokenKey&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,TokenKey&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct AuthRequest : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.AuthRequest";
        }
        static string MD5()
        {
            return "942f55a07abf289c9224ebd1a651ad05";
        }
        AuthRequest()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sKey.resetDefautlt();
            sToken = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sKey, 1);
            _os.write(sToken, 2);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sKey, 1, true);
            _is.read(sToken, 2, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sKey"] = tars::JsonOutput::writeJson(sKey);
            p->value["sToken"] = tars::JsonOutput::writeJson(sToken);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sKey,pObj->value["sKey"], true);
            tars::JsonInput::readJson(sToken,pObj->value["sToken"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sKey,"sKey");
            _ds.display(sToken,"sToken");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sKey, true);
            _ds.displaySimple(sToken, false);
            return _os;
        }
    public:
        tars::TokenKey sKey;
        std::string sToken;
    };
    inline bool operator==(const AuthRequest&l, const AuthRequest&r)
    {
        return l.sKey == r.sKey && l.sToken == r.sToken;
    }
    inline bool operator!=(const AuthRequest&l, const AuthRequest&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const AuthRequest&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,AuthRequest&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct TokenRequest : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.TokenRequest";
        }
        static string MD5()
        {
            return "14e6636632c63fdfafc03fddb6c460ba";
        }
        TokenRequest()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            vObjName.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(vObjName, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(vObjName, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["vObjName"] = tars::JsonOutput::writeJson(vObjName);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(vObjName,pObj->value["vObjName"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(vObjName,"vObjName");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(vObjName, false);
            return _os;
        }
    public:
        vector<std::string> vObjName;
    };
    inline bool operator==(const TokenRequest&l, const TokenRequest&r)
    {
        return l.vObjName == r.vObjName;
    }
    inline bool operator!=(const TokenRequest&l, const TokenRequest&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const TokenRequest&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,TokenRequest&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct TokenResponse : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.TokenResponse";
        }
        static string MD5()
        {
            return "de50d7cd52dae5ef0d013ba49ccdf1a6";
        }
        TokenResponse()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sObjName = "";
            mTokens.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sObjName, 1);
            _os.write(mTokens, 2);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sObjName, 1, true);
            _is.read(mTokens, 2, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sObjName"] = tars::JsonOutput::writeJson(sObjName);
            p->value["mTokens"] = tars::JsonOutput::writeJson(mTokens);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sObjName,pObj->value["sObjName"], true);
            tars::JsonInput::readJson(mTokens,pObj->value["mTokens"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sObjName,"sObjName");
            _ds.display(mTokens,"mTokens");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sObjName, true);
            _ds.displaySimple(mTokens, false);
            return _os;
        }
    public:
        std::string sObjName;
        map<std::string, std::string> mTokens;
    };
    inline bool operator==(const TokenResponse&l, const TokenResponse&r)
    {
        return l.sObjName == r.sObjName && l.mTokens == r.mTokens;
    }
    inline bool operator!=(const TokenResponse&l, const TokenResponse&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const TokenResponse&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,TokenResponse&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct ApplyTokenRequest : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.ApplyTokenRequest";
        }
        static string MD5()
        {
            return "6c9a6c3f75eb20f4894fa49a6c7a8a22";
        }
        ApplyTokenRequest()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sKey.resetDefautlt();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sKey, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sKey, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sKey"] = tars::JsonOutput::writeJson(sKey);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sKey,pObj->value["sKey"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sKey,"sKey");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sKey, false);
            return _os;
        }
    public:
        tars::TokenKey sKey;
    };
    inline bool operator==(const ApplyTokenRequest&l, const ApplyTokenRequest&r)
    {
        return l.sKey == r.sKey;
    }
    inline bool operator!=(const ApplyTokenRequest&l, const ApplyTokenRequest&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const ApplyTokenRequest&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,ApplyTokenRequest&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct ApplyTokenResponse : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.ApplyTokenResponse";
        }
        static string MD5()
        {
            return "942f55a07abf289c9224ebd1a651ad05";
        }
        ApplyTokenResponse()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sKey.resetDefautlt();
            sToken = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sKey, 1);
            _os.write(sToken, 2);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sKey, 1, true);
            _is.read(sToken, 2, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sKey"] = tars::JsonOutput::writeJson(sKey);
            p->value["sToken"] = tars::JsonOutput::writeJson(sToken);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sKey,pObj->value["sKey"], true);
            tars::JsonInput::readJson(sToken,pObj->value["sToken"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sKey,"sKey");
            _ds.display(sToken,"sToken");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sKey, true);
            _ds.displaySimple(sToken, false);
            return _os;
        }
    public:
        tars::TokenKey sKey;
        std::string sToken;
    };
    inline bool operator==(const ApplyTokenResponse&l, const ApplyTokenResponse&r)
    {
        return l.sKey == r.sKey && l.sToken == r.sToken;
    }
    inline bool operator!=(const ApplyTokenResponse&l, const ApplyTokenResponse&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const ApplyTokenResponse&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,ApplyTokenResponse&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct DeleteTokenRequest : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.DeleteTokenRequest";
        }
        static string MD5()
        {
            return "6c9a6c3f75eb20f4894fa49a6c7a8a22";
        }
        DeleteTokenRequest()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sKey.resetDefautlt();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sKey, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sKey, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sKey"] = tars::JsonOutput::writeJson(sKey);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sKey,pObj->value["sKey"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sKey,"sKey");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sKey, false);
            return _os;
        }
    public:
        tars::TokenKey sKey;
    };
    inline bool operator==(const DeleteTokenRequest&l, const DeleteTokenRequest&r)
    {
        return l.sKey == r.sKey;
    }
    inline bool operator!=(const DeleteTokenRequest&l, const DeleteTokenRequest&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const DeleteTokenRequest&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,DeleteTokenRequest&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


    /* callback of async proxy for client */
    class AuthPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~AuthPrxCallback(){}
        virtual void callback_applyToken(const tars::ApplyTokenResponse& ret)
        { throw std::runtime_error("callback_applyToken() override incorrect."); }
        virtual void callback_applyToken_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_applyToken_exception() override incorrect."); }

        virtual void callback_authProcess(tars::Int32 ret)
        { throw std::runtime_error("callback_authProcess() override incorrect."); }
        virtual void callback_authProcess_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_authProcess_exception() override incorrect."); }

        virtual void callback_deleteToken(tars::Int32 ret)
        { throw std::runtime_error("callback_deleteToken() override incorrect."); }
        virtual void callback_deleteToken_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_deleteToken_exception() override incorrect."); }

        virtual void callback_getTokens(const vector<tars::TokenResponse>& ret)
        { throw std::runtime_error("callback_getTokens() override incorrect."); }
        virtual void callback_getTokens_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_getTokens_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Auth_all[]=
            {
                "applyToken",
                "authProcess",
                "deleteToken",
                "getTokens"
            };
            pair<string*, string*> r = equal_range(__Auth_all, __Auth_all+4, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Auth_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_applyToken_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::ApplyTokenResponse _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_applyToken(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_authProcess_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_authProcess(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_deleteToken_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_deleteToken(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getTokens_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    vector<tars::TokenResponse> _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_getTokens(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<AuthPrxCallback> AuthPrxCallbackPtr;

    //callback of promise async proxy for client
    class AuthPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~AuthPrxCallbackPromise(){}
    public:
        struct PromiseapplyToken: virtual public TC_HandleBase
        {
        public:
            tars::ApplyTokenResponse _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< AuthPrxCallbackPromise::PromiseapplyToken > PromiseapplyTokenPtr;

        AuthPrxCallbackPromise(const tars::Promise< AuthPrxCallbackPromise::PromiseapplyTokenPtr > &promise)
        : _promise_applyToken(promise)
        {}
        
        virtual void callback_applyToken(const AuthPrxCallbackPromise::PromiseapplyTokenPtr &ptr)
        {
            _promise_applyToken.setValue(ptr);
        }
        virtual void callback_applyToken_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:applyToken_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_applyToken.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< AuthPrxCallbackPromise::PromiseapplyTokenPtr > _promise_applyToken;

    public:
        struct PromiseauthProcess: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< AuthPrxCallbackPromise::PromiseauthProcess > PromiseauthProcessPtr;

        AuthPrxCallbackPromise(const tars::Promise< AuthPrxCallbackPromise::PromiseauthProcessPtr > &promise)
        : _promise_authProcess(promise)
        {}
        
        virtual void callback_authProcess(const AuthPrxCallbackPromise::PromiseauthProcessPtr &ptr)
        {
            _promise_authProcess.setValue(ptr);
        }
        virtual void callback_authProcess_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:authProcess_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_authProcess.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< AuthPrxCallbackPromise::PromiseauthProcessPtr > _promise_authProcess;

    public:
        struct PromisedeleteToken: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< AuthPrxCallbackPromise::PromisedeleteToken > PromisedeleteTokenPtr;

        AuthPrxCallbackPromise(const tars::Promise< AuthPrxCallbackPromise::PromisedeleteTokenPtr > &promise)
        : _promise_deleteToken(promise)
        {}
        
        virtual void callback_deleteToken(const AuthPrxCallbackPromise::PromisedeleteTokenPtr &ptr)
        {
            _promise_deleteToken.setValue(ptr);
        }
        virtual void callback_deleteToken_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:deleteToken_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_deleteToken.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< AuthPrxCallbackPromise::PromisedeleteTokenPtr > _promise_deleteToken;

    public:
        struct PromisegetTokens: virtual public TC_HandleBase
        {
        public:
            vector<tars::TokenResponse> _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< AuthPrxCallbackPromise::PromisegetTokens > PromisegetTokensPtr;

        AuthPrxCallbackPromise(const tars::Promise< AuthPrxCallbackPromise::PromisegetTokensPtr > &promise)
        : _promise_getTokens(promise)
        {}
        
        virtual void callback_getTokens(const AuthPrxCallbackPromise::PromisegetTokensPtr &ptr)
        {
            _promise_getTokens.setValue(ptr);
        }
        virtual void callback_getTokens_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:getTokens_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_getTokens.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< AuthPrxCallbackPromise::PromisegetTokensPtr > _promise_getTokens;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Auth_all[]=
            {
                "applyToken",
                "authProcess",
                "deleteToken",
                "getTokens"
            };

            pair<string*, string*> r = equal_range(__Auth_all, __Auth_all+4, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Auth_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_applyToken_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    AuthPrxCallbackPromise::PromiseapplyTokenPtr ptr = new AuthPrxCallbackPromise::PromiseapplyToken();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_applyToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_applyToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_applyToken(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_authProcess_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    AuthPrxCallbackPromise::PromiseauthProcessPtr ptr = new AuthPrxCallbackPromise::PromiseauthProcess();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_authProcess_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_authProcess_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_authProcess(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_deleteToken_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    AuthPrxCallbackPromise::PromisedeleteTokenPtr ptr = new AuthPrxCallbackPromise::PromisedeleteToken();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_deleteToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_deleteToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_deleteToken(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getTokens_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    AuthPrxCallbackPromise::PromisegetTokensPtr ptr = new AuthPrxCallbackPromise::PromisegetTokens();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_getTokens_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getTokens_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_getTokens(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<AuthPrxCallbackPromise> AuthPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class AuthCoroPrxCallback: public AuthPrxCallback
    {
    public:
        virtual ~AuthCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Auth_all[]=
            {
                "applyToken",
                "authProcess",
                "deleteToken",
                "getTokens"
            };

            pair<string*, string*> r = equal_range(__Auth_all, __Auth_all+4, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Auth_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_applyToken_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::ApplyTokenResponse _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_applyToken(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_applyToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_applyToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_authProcess_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_authProcess(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_authProcess_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_authProcess_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_deleteToken_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_deleteToken(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_deleteToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_deleteToken_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getTokens_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        vector<tars::TokenResponse> _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_getTokens(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_getTokens_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getTokens_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<AuthCoroPrxCallback> AuthCoroPrxCallbackPtr;

    /* proxy for client */
    class AuthProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::ApplyTokenResponse applyToken(const tars::ApplyTokenRequest & request,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"applyToken", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::ApplyTokenResponse _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_applyToken(AuthPrxCallbackPtr callback,const tars::ApplyTokenRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"applyToken", _os, context, _mStatus, callback);
        }
        
        tars::Future< AuthPrxCallbackPromise::PromiseapplyTokenPtr > promise_async_applyToken(const tars::ApplyTokenRequest &request,const map<string, string>& context)
        {
            tars::Promise< AuthPrxCallbackPromise::PromiseapplyTokenPtr > promise;
            AuthPrxCallbackPromisePtr callback = new AuthPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"applyToken", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_applyToken(AuthCoroPrxCallbackPtr callback,const tars::ApplyTokenRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"applyToken", _os, context, _mStatus, callback, true);
        }

        tars::Int32 authProcess(const tars::AuthRequest & request,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"authProcess", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_authProcess(AuthPrxCallbackPtr callback,const tars::AuthRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"authProcess", _os, context, _mStatus, callback);
        }
        
        tars::Future< AuthPrxCallbackPromise::PromiseauthProcessPtr > promise_async_authProcess(const tars::AuthRequest &request,const map<string, string>& context)
        {
            tars::Promise< AuthPrxCallbackPromise::PromiseauthProcessPtr > promise;
            AuthPrxCallbackPromisePtr callback = new AuthPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"authProcess", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_authProcess(AuthCoroPrxCallbackPtr callback,const tars::AuthRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"authProcess", _os, context, _mStatus, callback, true);
        }

        tars::Int32 deleteToken(const tars::DeleteTokenRequest & request,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"deleteToken", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_deleteToken(AuthPrxCallbackPtr callback,const tars::DeleteTokenRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"deleteToken", _os, context, _mStatus, callback);
        }
        
        tars::Future< AuthPrxCallbackPromise::PromisedeleteTokenPtr > promise_async_deleteToken(const tars::DeleteTokenRequest &request,const map<string, string>& context)
        {
            tars::Promise< AuthPrxCallbackPromise::PromisedeleteTokenPtr > promise;
            AuthPrxCallbackPromisePtr callback = new AuthPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"deleteToken", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_deleteToken(AuthCoroPrxCallbackPtr callback,const tars::DeleteTokenRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"deleteToken", _os, context, _mStatus, callback, true);
        }

        vector<tars::TokenResponse> getTokens(const tars::TokenRequest & request,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"getTokens", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            vector<tars::TokenResponse> _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_getTokens(AuthPrxCallbackPtr callback,const tars::TokenRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getTokens", _os, context, _mStatus, callback);
        }
        
        tars::Future< AuthPrxCallbackPromise::PromisegetTokensPtr > promise_async_getTokens(const tars::TokenRequest &request,const map<string, string>& context)
        {
            tars::Promise< AuthPrxCallbackPromise::PromisegetTokensPtr > promise;
            AuthPrxCallbackPromisePtr callback = new AuthPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getTokens", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_getTokens(AuthCoroPrxCallbackPtr callback,const tars::TokenRequest &request,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(request, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getTokens", _os, context, _mStatus, callback, true);
        }

        AuthProxy* tars_hash(int64_t key)
        {
            return (AuthProxy*)ServantProxy::tars_hash(key);
        }

        AuthProxy* tars_consistent_hash(int64_t key)
        {
            return (AuthProxy*)ServantProxy::tars_consistent_hash(key);
        }

        AuthProxy* tars_open_trace(bool traceParam = false)
        {
            return (AuthProxy*)ServantProxy::tars_open_trace(traceParam);
        }

        AuthProxy* tars_set_timeout(int msecond)
        {
            return (AuthProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "AuthProxy"; }
    };
    typedef tars::TC_AutoPtr<AuthProxy> AuthPrx;

    /* servant for server */
    class Auth : public tars::Servant
    {
    public:
        virtual ~Auth(){}
        virtual tars::ApplyTokenResponse applyToken(const tars::ApplyTokenRequest & request,tars::TarsCurrentPtr current) = 0;
        static void async_response_applyToken(tars::TarsCurrentPtr current, const tars::ApplyTokenResponse &_ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 authProcess(const tars::AuthRequest & request,tars::TarsCurrentPtr current) = 0;
        static void async_response_authProcess(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 deleteToken(const tars::DeleteTokenRequest & request,tars::TarsCurrentPtr current) = 0;
        static void async_response_deleteToken(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual vector<tars::TokenResponse> getTokens(const tars::TokenRequest & request,tars::TarsCurrentPtr current) = 0;
        static void async_response_getTokens(tars::TarsCurrentPtr current, const vector<tars::TokenResponse> &_ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__Auth_all[]=
            {
                "applyToken",
                "authProcess",
                "deleteToken",
                "getTokens"
            };

            pair<string*, string*> r = equal_range(__tars__Auth_all, __tars__Auth_all+4, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__Auth_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::ApplyTokenRequest request;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("request", request);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(request, _jsonPtr->value["request"], true);
                    }
                    else
                    {
                        _is.read(request, 1, true);
                    }
                    tars::ApplyTokenResponse _ret = applyToken(request, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::AuthRequest request;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("request", request);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(request, _jsonPtr->value["request"], true);
                    }
                    else
                    {
                        _is.read(request, 1, true);
                    }
                    tars::Int32 _ret = authProcess(request, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::DeleteTokenRequest request;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("request", request);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(request, _jsonPtr->value["request"], true);
                    }
                    else
                    {
                        _is.read(request, 1, true);
                    }
                    tars::Int32 _ret = deleteToken(request, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::TokenRequest request;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("request", request);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(request, _jsonPtr->value["request"], true);
                    }
                    else
                    {
                        _is.read(request, 1, true);
                    }
                    vector<tars::TokenResponse> _ret = getTokens(request, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
