// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.7.
// **********************************************************************

#ifndef __STATF_H_
#define __STATF_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{
    struct StatMicMsgHead : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.StatMicMsgHead";
        }
        static string MD5()
        {
            return "0128910389fa508b176d044a2aaa8a12";
        }
        StatMicMsgHead()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            masterName = "";
            slaveName = "";
            interfaceName = "";
            masterIp = "";
            slaveIp = "";
            slavePort = 0;
            returnValue = 0;
            slaveSetName = "";
            slaveSetArea = "";
            slaveSetID = "";
            tarsVersion = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(masterName, 0);
            _os.write(slaveName, 1);
            _os.write(interfaceName, 2);
            _os.write(masterIp, 3);
            _os.write(slaveIp, 4);
            _os.write(slavePort, 5);
            _os.write(returnValue, 6);
            if (slaveSetName != "")
            {
                _os.write(slaveSetName, 7);
            }
            if (slaveSetArea != "")
            {
                _os.write(slaveSetArea, 8);
            }
            if (slaveSetID != "")
            {
                _os.write(slaveSetID, 9);
            }
            if (tarsVersion != "")
            {
                _os.write(tarsVersion, 10);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(masterName, 0, true);
            _is.read(slaveName, 1, true);
            _is.read(interfaceName, 2, true);
            _is.read(masterIp, 3, true);
            _is.read(slaveIp, 4, true);
            _is.read(slavePort, 5, true);
            _is.read(returnValue, 6, true);
            _is.read(slaveSetName, 7, false);
            _is.read(slaveSetArea, 8, false);
            _is.read(slaveSetID, 9, false);
            _is.read(tarsVersion, 10, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["masterName"] = tars::JsonOutput::writeJson(masterName);
            p->value["slaveName"] = tars::JsonOutput::writeJson(slaveName);
            p->value["interfaceName"] = tars::JsonOutput::writeJson(interfaceName);
            p->value["masterIp"] = tars::JsonOutput::writeJson(masterIp);
            p->value["slaveIp"] = tars::JsonOutput::writeJson(slaveIp);
            p->value["slavePort"] = tars::JsonOutput::writeJson(slavePort);
            p->value["returnValue"] = tars::JsonOutput::writeJson(returnValue);
            p->value["slaveSetName"] = tars::JsonOutput::writeJson(slaveSetName);
            p->value["slaveSetArea"] = tars::JsonOutput::writeJson(slaveSetArea);
            p->value["slaveSetID"] = tars::JsonOutput::writeJson(slaveSetID);
            p->value["tarsVersion"] = tars::JsonOutput::writeJson(tarsVersion);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(masterName,pObj->value["masterName"], true);
            tars::JsonInput::readJson(slaveName,pObj->value["slaveName"], true);
            tars::JsonInput::readJson(interfaceName,pObj->value["interfaceName"], true);
            tars::JsonInput::readJson(masterIp,pObj->value["masterIp"], true);
            tars::JsonInput::readJson(slaveIp,pObj->value["slaveIp"], true);
            tars::JsonInput::readJson(slavePort,pObj->value["slavePort"], true);
            tars::JsonInput::readJson(returnValue,pObj->value["returnValue"], true);
            tars::JsonInput::readJson(slaveSetName,pObj->value["slaveSetName"], false);
            tars::JsonInput::readJson(slaveSetArea,pObj->value["slaveSetArea"], false);
            tars::JsonInput::readJson(slaveSetID,pObj->value["slaveSetID"], false);
            tars::JsonInput::readJson(tarsVersion,pObj->value["tarsVersion"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(masterName,"masterName");
            _ds.display(slaveName,"slaveName");
            _ds.display(interfaceName,"interfaceName");
            _ds.display(masterIp,"masterIp");
            _ds.display(slaveIp,"slaveIp");
            _ds.display(slavePort,"slavePort");
            _ds.display(returnValue,"returnValue");
            _ds.display(slaveSetName,"slaveSetName");
            _ds.display(slaveSetArea,"slaveSetArea");
            _ds.display(slaveSetID,"slaveSetID");
            _ds.display(tarsVersion,"tarsVersion");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(masterName, true);
            _ds.displaySimple(slaveName, true);
            _ds.displaySimple(interfaceName, true);
            _ds.displaySimple(masterIp, true);
            _ds.displaySimple(slaveIp, true);
            _ds.displaySimple(slavePort, true);
            _ds.displaySimple(returnValue, true);
            _ds.displaySimple(slaveSetName, true);
            _ds.displaySimple(slaveSetArea, true);
            _ds.displaySimple(slaveSetID, true);
            _ds.displaySimple(tarsVersion, false);
            return _os;
        }
    public:
        std::string masterName;
        std::string slaveName;
        std::string interfaceName;
        std::string masterIp;
        std::string slaveIp;
        tars::Int32 slavePort;
        tars::Int32 returnValue;
        std::string slaveSetName;
        std::string slaveSetArea;
        std::string slaveSetID;
        std::string tarsVersion;
    };
    inline bool operator==(const StatMicMsgHead&l, const StatMicMsgHead&r)
    {
        return l.masterName == r.masterName && l.slaveName == r.slaveName && l.interfaceName == r.interfaceName && l.masterIp == r.masterIp && l.slaveIp == r.slaveIp && l.slavePort == r.slavePort && l.returnValue == r.returnValue && l.slaveSetName == r.slaveSetName && l.slaveSetArea == r.slaveSetArea && l.slaveSetID == r.slaveSetID && l.tarsVersion == r.tarsVersion;
    }
    inline bool operator!=(const StatMicMsgHead&l, const StatMicMsgHead&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const StatMicMsgHead&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,StatMicMsgHead&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }
    inline bool operator<(const StatMicMsgHead&l, const StatMicMsgHead&r)
    {
        if(l.masterName != r.masterName)  return (l.masterName < r.masterName);
        if(l.slaveName != r.slaveName)  return (l.slaveName < r.slaveName);
        if(l.interfaceName != r.interfaceName)  return (l.interfaceName < r.interfaceName);
        if(l.masterIp != r.masterIp)  return (l.masterIp < r.masterIp);
        if(l.slaveIp != r.slaveIp)  return (l.slaveIp < r.slaveIp);
        if(l.slavePort != r.slavePort)  return (l.slavePort < r.slavePort);
        if(l.returnValue != r.returnValue)  return (l.returnValue < r.returnValue);
        if(l.slaveSetName != r.slaveSetName)  return (l.slaveSetName < r.slaveSetName);
        if(l.slaveSetArea != r.slaveSetArea)  return (l.slaveSetArea < r.slaveSetArea);
        if(l.slaveSetID != r.slaveSetID)  return (l.slaveSetID < r.slaveSetID);
        if(l.tarsVersion != r.tarsVersion)  return (l.tarsVersion < r.tarsVersion);
        return false;
    }
    inline bool operator<=(const StatMicMsgHead&l, const StatMicMsgHead&r)
    {
        return !(r < l);
    }
    inline bool operator>(const StatMicMsgHead&l, const StatMicMsgHead&r)
    {
        return r < l;
    }
    inline bool operator>=(const StatMicMsgHead&l, const StatMicMsgHead&r)
    {
        return !(l < r);
    }

    struct StatMicMsgBody : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.StatMicMsgBody";
        }
        static string MD5()
        {
            return "8de4fb59ea3ed2b2697672a500533d67";
        }
        StatMicMsgBody()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            count = 0;
            timeoutCount = 0;
            execCount = 0;
            intervalCount.clear();
            totalRspTime = 0;
            maxRspTime = 0;
            minRspTime = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(count, 0);
            _os.write(timeoutCount, 1);
            _os.write(execCount, 2);
            _os.write(intervalCount, 3);
            _os.write(totalRspTime, 4);
            _os.write(maxRspTime, 5);
            _os.write(minRspTime, 6);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(count, 0, true);
            _is.read(timeoutCount, 1, true);
            _is.read(execCount, 2, true);
            _is.read(intervalCount, 3, true);
            _is.read(totalRspTime, 4, true);
            _is.read(maxRspTime, 5, true);
            _is.read(minRspTime, 6, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["count"] = tars::JsonOutput::writeJson(count);
            p->value["timeoutCount"] = tars::JsonOutput::writeJson(timeoutCount);
            p->value["execCount"] = tars::JsonOutput::writeJson(execCount);
            p->value["intervalCount"] = tars::JsonOutput::writeJson(intervalCount);
            p->value["totalRspTime"] = tars::JsonOutput::writeJson(totalRspTime);
            p->value["maxRspTime"] = tars::JsonOutput::writeJson(maxRspTime);
            p->value["minRspTime"] = tars::JsonOutput::writeJson(minRspTime);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(count,pObj->value["count"], true);
            tars::JsonInput::readJson(timeoutCount,pObj->value["timeoutCount"], true);
            tars::JsonInput::readJson(execCount,pObj->value["execCount"], true);
            tars::JsonInput::readJson(intervalCount,pObj->value["intervalCount"], true);
            tars::JsonInput::readJson(totalRspTime,pObj->value["totalRspTime"], true);
            tars::JsonInput::readJson(maxRspTime,pObj->value["maxRspTime"], true);
            tars::JsonInput::readJson(minRspTime,pObj->value["minRspTime"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(count,"count");
            _ds.display(timeoutCount,"timeoutCount");
            _ds.display(execCount,"execCount");
            _ds.display(intervalCount,"intervalCount");
            _ds.display(totalRspTime,"totalRspTime");
            _ds.display(maxRspTime,"maxRspTime");
            _ds.display(minRspTime,"minRspTime");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(count, true);
            _ds.displaySimple(timeoutCount, true);
            _ds.displaySimple(execCount, true);
            _ds.displaySimple(intervalCount, true);
            _ds.displaySimple(totalRspTime, true);
            _ds.displaySimple(maxRspTime, true);
            _ds.displaySimple(minRspTime, false);
            return _os;
        }
    public:
        tars::Int32 count;
        tars::Int32 timeoutCount;
        tars::Int32 execCount;
        map<tars::Int32, tars::Int32> intervalCount;
        tars::Int64 totalRspTime;
        tars::Int32 maxRspTime;
        tars::Int32 minRspTime;
    };
    inline bool operator==(const StatMicMsgBody&l, const StatMicMsgBody&r)
    {
        return l.count == r.count && l.timeoutCount == r.timeoutCount && l.execCount == r.execCount && l.intervalCount == r.intervalCount && l.totalRspTime == r.totalRspTime && l.maxRspTime == r.maxRspTime && l.minRspTime == r.minRspTime;
    }
    inline bool operator!=(const StatMicMsgBody&l, const StatMicMsgBody&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const StatMicMsgBody&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,StatMicMsgBody&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct StatSampleMsg : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.StatSampleMsg";
        }
        static string MD5()
        {
            return "974f999adca923a94a5e3b4d770e9b97";
        }
        StatSampleMsg()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            unid = "";
            masterName = "";
            slaveName = "";
            interfaceName = "";
            masterIp = "";
            slaveIp = "";
            depth = 0;
            width = 0;
            parentWidth = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(unid, 0);
            _os.write(masterName, 1);
            _os.write(slaveName, 2);
            _os.write(interfaceName, 3);
            _os.write(masterIp, 4);
            _os.write(slaveIp, 5);
            _os.write(depth, 6);
            _os.write(width, 7);
            _os.write(parentWidth, 8);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(unid, 0, true);
            _is.read(masterName, 1, true);
            _is.read(slaveName, 2, true);
            _is.read(interfaceName, 3, true);
            _is.read(masterIp, 4, true);
            _is.read(slaveIp, 5, true);
            _is.read(depth, 6, true);
            _is.read(width, 7, true);
            _is.read(parentWidth, 8, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["unid"] = tars::JsonOutput::writeJson(unid);
            p->value["masterName"] = tars::JsonOutput::writeJson(masterName);
            p->value["slaveName"] = tars::JsonOutput::writeJson(slaveName);
            p->value["interfaceName"] = tars::JsonOutput::writeJson(interfaceName);
            p->value["masterIp"] = tars::JsonOutput::writeJson(masterIp);
            p->value["slaveIp"] = tars::JsonOutput::writeJson(slaveIp);
            p->value["depth"] = tars::JsonOutput::writeJson(depth);
            p->value["width"] = tars::JsonOutput::writeJson(width);
            p->value["parentWidth"] = tars::JsonOutput::writeJson(parentWidth);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(unid,pObj->value["unid"], true);
            tars::JsonInput::readJson(masterName,pObj->value["masterName"], true);
            tars::JsonInput::readJson(slaveName,pObj->value["slaveName"], true);
            tars::JsonInput::readJson(interfaceName,pObj->value["interfaceName"], true);
            tars::JsonInput::readJson(masterIp,pObj->value["masterIp"], true);
            tars::JsonInput::readJson(slaveIp,pObj->value["slaveIp"], true);
            tars::JsonInput::readJson(depth,pObj->value["depth"], true);
            tars::JsonInput::readJson(width,pObj->value["width"], true);
            tars::JsonInput::readJson(parentWidth,pObj->value["parentWidth"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(unid,"unid");
            _ds.display(masterName,"masterName");
            _ds.display(slaveName,"slaveName");
            _ds.display(interfaceName,"interfaceName");
            _ds.display(masterIp,"masterIp");
            _ds.display(slaveIp,"slaveIp");
            _ds.display(depth,"depth");
            _ds.display(width,"width");
            _ds.display(parentWidth,"parentWidth");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(unid, true);
            _ds.displaySimple(masterName, true);
            _ds.displaySimple(slaveName, true);
            _ds.displaySimple(interfaceName, true);
            _ds.displaySimple(masterIp, true);
            _ds.displaySimple(slaveIp, true);
            _ds.displaySimple(depth, true);
            _ds.displaySimple(width, true);
            _ds.displaySimple(parentWidth, false);
            return _os;
        }
    public:
        std::string unid;
        std::string masterName;
        std::string slaveName;
        std::string interfaceName;
        std::string masterIp;
        std::string slaveIp;
        tars::Int32 depth;
        tars::Int32 width;
        tars::Int32 parentWidth;
    };
    inline bool operator==(const StatSampleMsg&l, const StatSampleMsg&r)
    {
        return l.unid == r.unid && l.masterName == r.masterName && l.slaveName == r.slaveName && l.interfaceName == r.interfaceName && l.masterIp == r.masterIp && l.slaveIp == r.slaveIp && l.depth == r.depth && l.width == r.width && l.parentWidth == r.parentWidth;
    }
    inline bool operator!=(const StatSampleMsg&l, const StatSampleMsg&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const StatSampleMsg&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,StatSampleMsg&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct ProxyInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.ProxyInfo";
        }
        static string MD5()
        {
            return "e2c4c8305a9075ebd29458f561b1f204";
        }
        ProxyInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            bFromClient = true;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(bFromClient, 0);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(bFromClient, 0, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["bFromClient"] = tars::JsonOutput::writeJson(bFromClient);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(bFromClient,pObj->value["bFromClient"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(bFromClient,"bFromClient");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(bFromClient, false);
            return _os;
        }
    public:
        tars::Bool bFromClient;
    };
    inline bool operator==(const ProxyInfo&l, const ProxyInfo&r)
    {
        return l.bFromClient == r.bFromClient;
    }
    inline bool operator!=(const ProxyInfo&l, const ProxyInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const ProxyInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,ProxyInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


    /* callback of async proxy for client */
    class StatFPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~StatFPrxCallback(){}
        virtual void callback_reportMicMsg(tars::Int32 ret)
        { throw std::runtime_error("callback_reportMicMsg() override incorrect."); }
        virtual void callback_reportMicMsg_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_reportMicMsg_exception() override incorrect."); }

        virtual void callback_reportSampleMsg(tars::Int32 ret)
        { throw std::runtime_error("callback_reportSampleMsg() override incorrect."); }
        virtual void callback_reportSampleMsg_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_reportSampleMsg_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __StatF_all[]=
            {
                "reportMicMsg",
                "reportSampleMsg"
            };
            pair<string*, string*> r = equal_range(__StatF_all, __StatF_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __StatF_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportMicMsg_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_reportMicMsg(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportSampleMsg_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_reportSampleMsg(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<StatFPrxCallback> StatFPrxCallbackPtr;

    //callback of promise async proxy for client
    class StatFPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~StatFPrxCallbackPromise(){}
    public:
        struct PromisereportMicMsg: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< StatFPrxCallbackPromise::PromisereportMicMsg > PromisereportMicMsgPtr;

        StatFPrxCallbackPromise(const tars::Promise< StatFPrxCallbackPromise::PromisereportMicMsgPtr > &promise)
        : _promise_reportMicMsg(promise)
        {}
        
        virtual void callback_reportMicMsg(const StatFPrxCallbackPromise::PromisereportMicMsgPtr &ptr)
        {
            _promise_reportMicMsg.setValue(ptr);
        }
        virtual void callback_reportMicMsg_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:reportMicMsg_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_reportMicMsg.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< StatFPrxCallbackPromise::PromisereportMicMsgPtr > _promise_reportMicMsg;

    public:
        struct PromisereportSampleMsg: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< StatFPrxCallbackPromise::PromisereportSampleMsg > PromisereportSampleMsgPtr;

        StatFPrxCallbackPromise(const tars::Promise< StatFPrxCallbackPromise::PromisereportSampleMsgPtr > &promise)
        : _promise_reportSampleMsg(promise)
        {}
        
        virtual void callback_reportSampleMsg(const StatFPrxCallbackPromise::PromisereportSampleMsgPtr &ptr)
        {
            _promise_reportSampleMsg.setValue(ptr);
        }
        virtual void callback_reportSampleMsg_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:reportSampleMsg_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_reportSampleMsg.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< StatFPrxCallbackPromise::PromisereportSampleMsgPtr > _promise_reportSampleMsg;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __StatF_all[]=
            {
                "reportMicMsg",
                "reportSampleMsg"
            };

            pair<string*, string*> r = equal_range(__StatF_all, __StatF_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __StatF_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportMicMsg_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    StatFPrxCallbackPromise::PromisereportMicMsgPtr ptr = new StatFPrxCallbackPromise::PromisereportMicMsg();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_reportMicMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportMicMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_reportMicMsg(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportSampleMsg_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    StatFPrxCallbackPromise::PromisereportSampleMsgPtr ptr = new StatFPrxCallbackPromise::PromisereportSampleMsg();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_reportSampleMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportSampleMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_reportSampleMsg(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<StatFPrxCallbackPromise> StatFPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class StatFCoroPrxCallback: public StatFPrxCallback
    {
    public:
        virtual ~StatFCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __StatF_all[]=
            {
                "reportMicMsg",
                "reportSampleMsg"
            };

            pair<string*, string*> r = equal_range(__StatF_all, __StatF_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __StatF_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportMicMsg_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_reportMicMsg(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_reportMicMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportMicMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportSampleMsg_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_reportSampleMsg(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_reportSampleMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportSampleMsg_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<StatFCoroPrxCallback> StatFCoroPrxCallbackPtr;

    /* proxy for client */
    class StatFProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 reportMicMsg(const map<tars::StatMicMsgHead, tars::StatMicMsgBody> & msg,tars::Bool bFromClient,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            _os.write(bFromClient, 2);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"reportMicMsg", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_reportMicMsg(StatFPrxCallbackPtr callback,const map<tars::StatMicMsgHead, tars::StatMicMsgBody> &msg,tars::Bool bFromClient,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            _os.write(bFromClient, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportMicMsg", _os, context, _mStatus, callback);
        }
        
        tars::Future< StatFPrxCallbackPromise::PromisereportMicMsgPtr > promise_async_reportMicMsg(const map<tars::StatMicMsgHead, tars::StatMicMsgBody> &msg,tars::Bool bFromClient,const map<string, string>& context)
        {
            tars::Promise< StatFPrxCallbackPromise::PromisereportMicMsgPtr > promise;
            StatFPrxCallbackPromisePtr callback = new StatFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            _os.write(bFromClient, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportMicMsg", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_reportMicMsg(StatFCoroPrxCallbackPtr callback,const map<tars::StatMicMsgHead, tars::StatMicMsgBody> &msg,tars::Bool bFromClient,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            _os.write(bFromClient, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportMicMsg", _os, context, _mStatus, callback, true);
        }

        tars::Int32 reportSampleMsg(const vector<tars::StatSampleMsg> & msg,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"reportSampleMsg", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_reportSampleMsg(StatFPrxCallbackPtr callback,const vector<tars::StatSampleMsg> &msg,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportSampleMsg", _os, context, _mStatus, callback);
        }
        
        tars::Future< StatFPrxCallbackPromise::PromisereportSampleMsgPtr > promise_async_reportSampleMsg(const vector<tars::StatSampleMsg> &msg,const map<string, string>& context)
        {
            tars::Promise< StatFPrxCallbackPromise::PromisereportSampleMsgPtr > promise;
            StatFPrxCallbackPromisePtr callback = new StatFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportSampleMsg", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_reportSampleMsg(StatFCoroPrxCallbackPtr callback,const vector<tars::StatSampleMsg> &msg,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(msg, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportSampleMsg", _os, context, _mStatus, callback, true);
        }

        StatFProxy* tars_hash(int64_t key)
        {
            return (StatFProxy*)ServantProxy::tars_hash(key);
        }

        StatFProxy* tars_consistent_hash(int64_t key)
        {
            return (StatFProxy*)ServantProxy::tars_consistent_hash(key);
        }

        StatFProxy* tars_open_trace(bool traceParam = false)
        {
            return (StatFProxy*)ServantProxy::tars_open_trace(traceParam);
        }

        StatFProxy* tars_set_timeout(int msecond)
        {
            return (StatFProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "StatFProxy"; }
    };
    typedef tars::TC_AutoPtr<StatFProxy> StatFPrx;

    /* servant for server */
    class StatF : public tars::Servant
    {
    public:
        virtual ~StatF(){}
        virtual tars::Int32 reportMicMsg(const map<tars::StatMicMsgHead, tars::StatMicMsgBody> & msg,tars::Bool bFromClient,tars::TarsCurrentPtr current) = 0;
        static void async_response_reportMicMsg(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 reportSampleMsg(const vector<tars::StatSampleMsg> & msg,tars::TarsCurrentPtr current) = 0;
        static void async_response_reportSampleMsg(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__StatF_all[]=
            {
                "reportMicMsg",
                "reportSampleMsg"
            };

            pair<string*, string*> r = equal_range(__tars__StatF_all, __tars__StatF_all+2, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__StatF_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    map<tars::StatMicMsgHead, tars::StatMicMsgBody> msg;
                    tars::Bool bFromClient = false;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("msg", msg);
                        tarsAttr.get("bFromClient", bFromClient);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(msg, _jsonPtr->value["msg"], true);
                        tars::JsonInput::readJson(bFromClient, _jsonPtr->value["bFromClient"], true);
                    }
                    else
                    {
                        _is.read(msg, 1, true);
                        _is.read(bFromClient, 2, true);
                    }
                    tars::Int32 _ret = reportMicMsg(msg,bFromClient, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    vector<tars::StatSampleMsg> msg;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("msg", msg);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(msg, _jsonPtr->value["msg"], true);
                    }
                    else
                    {
                        _is.read(msg, 1, true);
                    }
                    tars::Int32 _ret = reportSampleMsg(msg, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
