name: C/C++ mac

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: brew install bison flex cmake;  cmake --version
    - name: git
      run: git submodule update --init --recursive
    - name: configure
      run: mkdir build;cd build;cmake .. -DTARS_MYSQL=ON -DTARS_SSL=ON -DTARS_HTTP2=ON -DTARS_PROTOBUF=ON
    - name: make
      run: cd build; make -j4

